name: Snyk Security Scan

on:
  push:
    branches: ["main, dev"]
  pull_request:
    branches: ["main, dev"]

jobs:
  snyk:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      # ---------------------------------
      # Checkout
      # ---------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------------
      # Setup .NET
      # ---------------------------------
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # ---------------------------------
      # Restore Dependencies (REQUIRED for Snyk SCA)
      # ---------------------------------
      - name: Restore dependencies
        run: dotnet restore spot-service.sln

      # ---------------------------------
      # Setup Snyk CLI
      # ---------------------------------
      - name: Setup Snyk
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # ---------------------------------
      # SCA - Open Source Scan
      # ---------------------------------
      - name: Run Snyk Open Source
        run: snyk test --file=spot-service.sln --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # ---------------------------------
      # SAST - Code Scan
      # ---------------------------------
      - name: Run Snyk Code
        run: snyk code test --severity-threshold=high
        working-directory: ./spot-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # ---------------------------------
      # Build Docker Image
      # ---------------------------------
      - name: Build Docker Image
        run: docker build -t spot-service:latest .
        working-directory: ./spot-service

      # ---------------------------------
      # Container Scan
      # ---------------------------------
      - name: Run Snyk Container
        run: snyk container test spot-service:latest --file=Dockerfile --severity-threshold=high
        working-directory: ./spot-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
