name: Unit Test with Coverage

on:
  pull_request:
    branches: ["dev"]

jobs:
  unit-test-with-coverage:
    uses: NUS-ISS-MTech-SE33-PT/workflows/.github/workflows/dotnet-unit-test-with-coverage.yml@v1.0.4
    with:
      unit-test-dll-path: './spot-submission-service.UnitTests/bin/Release/net9.0/spot-submission-service.UnitTests.dll'

    